{{- if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "python-webapp.fullname" . }}
  labels:
    {{- include "python-webapp.labels" . | nindent 4 }}
spec:
{{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "python-webapp.selectorLabels" . | nindent 6 }}
{{- end }}
